version: '3'

services:
  confax:
    build: .
    container_name: confax
    restart: unless-stopped
    environment:
      - BOT_TOKEN=
      - FINNHUB_API_KEY=
    volumes:
      - './src/guilds:/usr/share/app/src/guilds'
